name: altakamul_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  google_fonts: ^6.2.1
  infinite_scroll_pagination: ^5.1.0
  another_toast:
    git:
      url: https://github.com/alaaeddine-awata/another_toast.git

  # State Management & Architecture
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.2.0

  # Navigation
  go_router: ^16.2.4

  # Network & API
  dio: ^5.9.0
  retrofit: ^4.7.3
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0

  # Data Handling
  multiple_result: ^5.2.0
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Quality & Linting
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.9.0
  retrofit_generator: ^10.0.6
  freezed: ^3.2.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
